### PR TITLE
Working version for rails 5.1.x

### PR DESCRIPTION
**Pull request by vraravam**
@pcreux - As mentioned in another issue, I have this working for a rails 5.1.3 codebase. Please consider merging. If you want, I can also come on a video chat to show my code for the app - and we can compare where your test app vs mine are inconsistent.

### CODE REVIEW

**Review by pcreux — COMMENTED** [review]
We could make this >= 4.2 like it was before.

The tests are failing because Rails 5 generates errors that don't match the Rails 4 ones. We just need to find a way to force the tests to generate a rails 4 app. Forcing the version in the Gemfile would work.

I can give that a try later this week.

**Comment by vraravam** [comment]
@pcreux : Yes - that would be awesome!

**Comment by vraravam** [comment]
@pcreux - sorry, its been 2 years - can this go forward? Or shall i close the PR?

**Comment by pcreux** [comment]
@vraravam Sorry about that! I'll look into it next week.

**Comment by pcreux** [comment]
I've just released version 0.5.0 that supports Rails 5 and 6! Thank you for pigging me @vraravam!

**Pull request closed without merging**
